trigger:
  - master

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Test
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'

  - job: PackCore
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'pack'
          packagesToPack: 'Lanchat.Core/Lanchat.Core.csproj'
          packDirectory: '$(Build.ArtifactStagingDirectory)/Core'
          versioningScheme: 'off'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Core'
          ArtifactName: 'Core'
          publishLocation: 'Container'

  - job: PackTerminal
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'Lanchat.Terminal/Lanchat.Terminal.csproj'
        arguments: '-c Release -p:PublishSingleFile=true --self-contained true -r win-x86 -o $(Build.ArtifactStagingDirectory)/Terminal'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Terminal'
        ArtifactName: 'Terminal'
        publishLocation: 'Container'