trigger:
  - master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build and test
    jobs:
    - job: Build
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
    - job: Test
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
    
  - stage: Publish core package
    jobs:
      - job: Pack
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'pack'
            packagesToPack: 'Lanchat.Core/Lanchat.Core.csproj'
            packDirectory: '$(Build.ArtifactStagingDirectory)/Core'
            versioningScheme: 'off'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/Core'
            ArtifactName: 'Core'
            publishLocation: 'Container'